apiVersion: v1
kind: Service
metadata:
  name: svc2
  labels:
    app: svc2
spec:
  type: NodePort
  ports:
    - port: 80 # the port that this service should serve on - note this is cluster internal
      targetPort: 8080 # the container listens here
  selector:
    app: svc2
