apiVersion: v1
kind: Service
metadata:
  name: svc2
  labels:
    app: svc2
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  #type: LoadBalancer
  type: NodePort
  #externalIPs:
  #  - 192.168.99.100
  ports:
    # the port that this service should serve on
    - port: 8080
  selector:
    app: svc2
